"""Replay-from-raw_events must yield byte-identical projections.

This is the canonical regression test for the event-sourcing contract: any
bug or schema change ships behind a replay. If replay does not reproduce the
projection, the system is not actually replayable, and the design is broken.
"""

from __future__ import annotations

import pytest

from app.hashing import compute_event_id
from app.tools.replay import truncate
from app.workers.pipeline import process_event, reset_pipeline_singletons


async def _seed_and_process(pool, payloads: list[dict]) -> list[str]:
    event_ids: list[str] = []
    for p in payloads:
        eid = compute_event_id(p, p.get("event_msg_id") or p.get("doc_ref") or p.get("event_id"))
        async with pool.acquire() as conn:
            await conn.execute(
                "INSERT INTO raw_events (event_id, payload, headers) VALUES ($1, $2::jsonb, '{}'::jsonb) ON CONFLICT DO NOTHING",
                eid,
                p,
            )
        event_ids.append(eid)
        await process_event(pool, eid)
    return event_ids


async def _snapshot(pool) -> dict:
    async with pool.acquire() as conn:
        ships = await conn.fetch(
            "SELECT vendor_id, external_id, state, last_applied_event_id, last_applied_ts, version FROM shipments ORDER BY external_id"
        )
        invs = await conn.fetch(
            "SELECT vendor_id, external_id, state, currency, amount_minor, last_applied_event_id, last_applied_ts, version FROM invoices ORDER BY external_id"
        )
        applied = await conn.fetch(
            "SELECT entity_id, event_id, target_state FROM applied_events ORDER BY entity_id, event_id"
        )
    return {
        "shipments": [dict(r) for r in ships],
        "invoices": [dict(r) for r in invs],
        "applied": [dict(r) for r in applied],
    }


@pytest.mark.asyncio
async def test_full_replay_produces_byte_identical_projection(seeded_db, fixture_payloads):
    pool = seeded_db
    reset_pipeline_singletons()

    ordered = [
        fixture_payloads["02_maersk_picked_up"],
        fixture_payloads["01_maersk_in_transit"],
        fixture_payloads["04_globalfreightpay_issued"],
        fixture_payloads["03_globalfreightpay_paid"],
        fixture_payloads["05_one_delivered"],
        fixture_payloads["06_marine_traffic_advisory"],
    ]
    event_ids = await _seed_and_process(pool, ordered)

    before = await _snapshot(pool)

    # Truncate everything except raw_events; entity_id values reset, so we
    # compare on (external_id, state, version) rather than entity_id.
    await truncate(pool)

    # Re-run the same events through the pipeline in the same order.
    for eid in event_ids:
        await process_event(pool, eid)

    after = await _snapshot(pool)

    # entity_id is generated by a sequence and resets after truncate, so we
    # compare on the externally-meaningful fields.
    def _strip(rows: list[dict], keys: list[str]) -> list[dict]:
        return [{k: r[k] for k in keys} for r in rows]

    assert _strip(
        before["shipments"],
        ["vendor_id", "external_id", "state", "last_applied_event_id", "last_applied_ts", "version"],
    ) == _strip(
        after["shipments"],
        ["vendor_id", "external_id", "state", "last_applied_event_id", "last_applied_ts", "version"],
    )
    assert _strip(
        before["invoices"],
        [
            "vendor_id",
            "external_id",
            "state",
            "currency",
            "amount_minor",
            "last_applied_event_id",
            "last_applied_ts",
            "version",
        ],
    ) == _strip(
        after["invoices"],
        [
            "vendor_id",
            "external_id",
            "state",
            "currency",
            "amount_minor",
            "last_applied_event_id",
            "last_applied_ts",
            "version",
        ],
    )

    # applied_events has entity_id which differs across truncate, but counts must match.
    assert len(before["applied"]) == len(after["applied"])
